In [1]:
# The code was removed by Watson Studio for sharing.

Country  Year      Status  Adult Mortality  infant deaths  Alcohol  \
0  Afghanistan  2015  Developing            263.0             62     0.01   
1  Afghanistan  2014  Developing            271.0             64     0.01   
2  Afghanistan  2013  Developing            268.0             66     0.01   
3  Afghanistan  2012  Developing            272.0             69     0.01   
4  Afghanistan  2011  Developing            275.0             71     0.01   

   percentage expenditure  Hepatitis B  Measles    BMI   ...  \
0               71.279624         65.0      1154   19.1  ...   
1               73.523582         62.0       492   18.6  ...   
2               73.219243         64.0       430   18.1  ...   
3               78.184215         67.0      2787   17.6  ...   
4                7.097109         68.0      3013   17.2  ...   

   Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0               8.16         65.0        0.1  584.259210  33736494.0   
1               8.18         62.0        0.1  612.696514    327582.0   
2               8.13         64.0        0.1  631.744976  31731688.0   
3               8.52         67.0        0.1  669.959000   3696958.0   
4               7.87         68.0        0.1   63.537231   2978599.0   

    thinness  1-19 years   thinness 5-9 years  \
0                   17.2                 17.3   
1                   17.5                 17.5   
2                   17.7                 17.7   
3                   17.9                 18.0   
4                   18.2                 18.2   

   Income composition of resources  Schooling  Life expectancy   
0                            0.479       10.1              65.0  
1                            0.476       10.0              59.9  
2                            0.470        9.9              59.9  
3                            0.463        9.8              59.5  
4                            0.454        9.5              59.2  

[5 rows x 22 columns]

In [2]:
df_data_1.Country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', "Côte d'Ivoire", 'Cabo Verde',
       'Cambodia', 'Cameroon', 'Canada', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
       'Georgia', 'Germany'

In [3]:
import numpy as np
df_data_1.dropna(how='any',inplace=True)

print(df_data_1.isnull().sum())


Country                            0
Year                               0
Status                             0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
Life expectancy                    0
dtype: int64


In [4]:
#encoding categorial data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder = LabelEncoder()
df_data_1['Country']=labelencoder.fit_transform(df_data_1['Country'])

df_data_1['Status']=labelencoder.fit_transform(df_data_1['Status'])

In [5]:
x=df_data_1.iloc[:,0:-1].values
y=df_data_1.iloc[:,-1].values



In [6]:
type(x)

numpy.ndarray

In [7]:
print(df_data_1.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1649 entries, 0 to 2937
Data columns (total 22 columns):
Country                            1649 non-null int64
Year                               1649 non-null int64
Status                             1649 non-null int64
Adult Mortality                    1649 non-null float64
infant deaths                      1649 non-null int64
Alcohol                            1649 non-null float64
percentage expenditure             1649 non-null float64
Hepatitis B                        1649 non-null float64
Measles                            1649 non-null int64
 BMI                               1649 non-null float64
under-five deaths                  1649 non-null int64
Polio                              1649 non-null float64
Total expenditure                  1649 non-null float64
Diphtheria                         1649 non-null float64
 HIV/AIDS                          1649 non-null float64
GDP                                1649 non-null f

In [8]:
x = np.nan_to_num(x.astype(np.float32))
x

array([[0.000e+00, 2.015e+03, 1.000e+00, ..., 1.730e+01, 4.790e-01,
        1.010e+01],
       [0.000e+00, 2.014e+03, 1.000e+00, ..., 1.750e+01, 4.760e-01,
        1.000e+01],
       [0.000e+00, 2.013e+03, 1.000e+00, ..., 1.770e+01, 4.700e-01,
        9.900e+00],
       ...,
       [1.320e+02, 2.002e+03, 1.000e+00, ..., 1.300e+00, 4.270e-01,
        1.000e+01],
       [1.320e+02, 2.001e+03, 1.000e+00, ..., 1.700e+00, 4.270e-01,
        9.800e+00],
       [1.320e+02, 2.000e+03, 1.000e+00, ..., 1.120e+01, 4.340e-01,
        9.800e+00]], dtype=float32)

In [9]:
y = np.nan_to_num(y.astype(np.float32))
y

array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ], dtype=float32)

In [10]:
np.isnan(x).any()

False

In [11]:
np.isfinite(x).any()

True

In [18]:
np.interp(x, (x.min(), x.max()), (-1, +1))

array([[-1.        , -0.99999689, -1.        , ..., -0.99999997,
        -1.        , -0.99999998],
       [-1.        , -0.99999689, -1.        , ..., -0.99999997,
        -1.        , -0.99999998],
       [-1.        , -0.99999689, -1.        , ..., -0.99999997,
        -1.        , -0.99999998],
       ...,
       [-0.9999998 , -0.99999691, -1.        , ..., -1.        ,
        -1.        , -0.99999998],
       [-0.9999998 , -0.99999691, -1.        , ..., -1.        ,
        -1.        , -0.99999998],
       [-0.9999998 , -0.99999691, -1.        , ..., -0.99999998,
        -1.        , -0.99999998]])

In [19]:
np.interp(y, (y.min(), y.max()), (-1, +1))

array([-0.06666667, -0.29333327, -0.29333327, ..., -0.96444448,
       -0.94222226, -0.91111111])

In [20]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
#fitting random forest to dataset
from sklearn.ensemble import RandomForestRegressor
DecisionTreeRegressionModel=RandomForestRegressor(n_estimators=10,random_state=0)
DecisionTreeRegressionModel.fit(x_train,y_train)

#predicting the test results
y_pred = DecisionTreeRegressionModel.predict(x_test)



from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_test, y_pred))
print(rms)

df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1 = df.head(25)
print(df1)

accuracy=DecisionTreeRegressionModel.score(x_test,y_test)

2.0193645352589855
       Actual  Predicted
0   57.500000  57.930001
1   81.699997  83.090001
2   75.599998  75.390000
3   56.599998  56.260001
4   61.400002  61.019999
5   79.900002  81.689999
6   54.000000  51.970000
7   51.000000  50.390000
8   45.500000  46.340000
9   72.900002  72.579999
10  81.000000  80.990000
11  74.699997  74.800000
12  80.000000  80.810000
13  73.599998  66.250000
14  78.000000  79.750001
15  45.599998  49.970000
16  46.000000  50.550000
17  71.199997  72.890000
18  73.900002  73.799999
19  73.000000  69.610001
20  75.900002  79.180000
21  67.599998  67.650000
22  67.000000  65.859999
23  74.900002  74.119999
24  73.699997  73.449999


In [21]:
accuracy

0.9528068089645216

In [22]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient
wml_credentials={
  "apikey": "_9W5ykpMbPnbrNesfzSmcMKxg1etCTmU6laCIdywxT6q",
  "iam_apikey_description": "Auto-generated for key 7491ff27-2af0-485d-86e1-ce3487e1389a",
  "iam_apikey_name": "wdp-writer",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/824cecd3061940bab89679d681931d1d::serviceid:ServiceId-e8985a07-2e35-4185-93da-4592f096145b",
  "instance_id": "c4080d6e-2480-460b-94cb-ec8203bff7e9",
  "url": "https://us-south.ml.cloud.ibm.com"
}

client = WatsonMachineLearningAPIClient(wml_credentials)
metadata={
    client.repository.ModelMetaNames.DESCRIPTION:'life prediction with python',
    client.repository.ModelMetaNames.AUTHOR_NAME:'Vaishnavi Patil',
    client.repository.ModelMetaNames.NAME:"Multilinear",
   # client.repository.ModelMetaNames.FRAMEWORK_NAME:"scikit-learn",
   # client.repository.ModelMetaNames.FRAMEWORK_VERSION:"0.22"
    
}
model_details=client.repository.store_model(DecisionTreeRegressionModel,meta_props=metadata)
print(model_details)
published_model_uid=client.repository.get_model_uid(model_details)
published_model_uid
created_deployment=client.deployments.create(published_model_uid,name="prediction")
scoring_endpoint = client.deployments.get_scoring_url(created_deployment)
client.deployments.list()

{'metadata': {'guid': '628fb435-f66b-4d19-bbab-65c30421bd29', 'url': 'https://us-south.ml.cloud.ibm.com/v3/wml_instances/c4080d6e-2480-460b-94cb-ec8203bff7e9/published_models/628fb435-f66b-4d19-bbab-65c30421bd29', 'created_at': '2020-07-02T17:19:35.020Z', 'modified_at': '2020-07-02T17:19:35.088Z'}, 'entity': {'runtime_environment': 'python-3.6', 'learning_configuration_url': 'https://us-south.ml.cloud.ibm.com/v3/wml_instances/c4080d6e-2480-460b-94cb-ec8203bff7e9/published_models/628fb435-f66b-4d19-bbab-65c30421bd29/learning_configuration', 'author': {'name': 'Vaishnavi Patil'}, 'name': 'Multilinear', 'description': 'life prediction with python', 'learning_iterations_url': 'https://us-south.ml.cloud.ibm.com/v3/wml_instances/c4080d6e-2480-460b-94cb-ec8203bff7e9/published_models/628fb435-f66b-4d19-bbab-65c30421bd29/learning_iterations', 'feedback_url': 'https://us-south.ml.cloud.ibm.com/v3/wml_instances/c4080d6e-2480-460b-94cb-ec8203bff7e9/published_models/628fb435-f66b-4d19-bbab-65c30421

In [23]:
scoring_endpoint

'https://us-south.ml.cloud.ibm.com/v3/wml_instances/c4080d6e-2480-460b-94cb-ec8203bff7e9/deployments/d9258a60-0ac6-4451-a67a-7ef822e16f94/online'